# Generated by Django 4.1.5 on 2023-01-31 03:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sportslifestyle', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='discount',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name='Review',
        ),
    ]
