# Generated by Django 4.1.5 on 2023-01-31 03:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sportslifestyle', '0002_alter_product_discount_delete_review'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='image',
        ),
    ]
