# Generated by Django 4.1.5 on 2023-02-02 05:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sportslifestyle', '0004_size_remove_product_size_product_size'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='quantity',
        ),
        migrations.RemoveField(
            model_name='product',
            name='size',
        ),
        migrations.AddField(
            model_name='product',
            name='variants',
            field=models.CharField(choices=[('None', 'None'), ('Size', 'Size')], default='None', max_length=100),
        ),
        migrations.CreateModel(
            name='ProductVariant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=0)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sportslifestyle.product')),
                ('size', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sportslifestyle.size')),
            ],
        ),
    ]
