# Generated by Django 4.1.5 on 2023-04-05 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sportslifestyle', '0010_comment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='newsletter',
            name='news_desc',
        ),
        migrations.AddField(
            model_name='newsletter',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
